---
- fail:
    msg: You should define atome_exporter_api.user variable
  when: atome_exporter_api.user is undefined

- fail:
    msg: You should define atome_exporter_api.password variable
  when: atome_exporter_api.password is undefined

- name: create atome_exporter system group
  group:
    name: atome_exporter
    system: true
    state: present
  register: atome_exporter_group

- name: create atome_exporter system user
  user:
    name: atome_exporter
    system: true
    shell: /usr/sbin/nologin
    group: "{{ atome_exporter_group.name }}"
    createhome: false
    home: /
  register: atome_exporter_user

- name: copy binary to app home
  copy:
    src: ../build/atome_exporter
    dest: "/usr/local/bin"
    owner: "{{ atome_exporter_user.name }}"
    group: "{{ atome_exporter_group.name }}"
    mode: 0755
  
- name: create systemd service unit
  template:
    src: atome_exporter.service.j2
    dest: /etc/systemd/system/atome_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart atome_exporter