{
 "title": "Consommation",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Consommation aujourd'hui",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    { "expr": "atome_consumption", "legendFormat": "WH" }
   ]
  },
  {
   "title": "Coût de la consommation",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 6, "y": 0 },
   "targets": [
    { "expr": "atome_price" }
   ]
  },
  {
   "title": "Émission de CO2 aujourd'hui",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "format": "massg",
   "valueName": "current",
   "targets": [
    { "expr": "atome_co2impact" }
   ]
  },
  {
   "title": "Consommation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "atome_consumption", "legendFormat": "W" }
   ]
  },
  {
   "title": "Émission de CO2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "atome_co2impact", "legendFormat": "CO2 g" }
   ]
  }
 ]
}