before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/atome_exporter/main.go
    env:
      - CGO_ENABLED=0
    goos:
    - darwin
    - linux
    goarch:
    - amd64
    - arm
    - arm64
    goarm:
    - 6
    - 7
    ignore:
    - goos: darwin
      goarch: arm

archives:
  - replacements:
      darwin: mac

checksum:
  algorithm: sha512

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
